SS Payton
friends-library/catherine-payton pull request #6
Opened 2019-03-12 05:38 UTC by maijapapaya

@jaredh159 @Henderjay

2019-03-12 05:44 UTC, maijapapaya commented
So I didn't want to mess with Ann Branson anymore after the problems (I messaged Jared), so on this one I just searched for her name because I was having the same problems searching for that syntax thing. I didn't want to do anything more in AB until you had a chance to look at it. Are you aware of any letters from the authors that aren't signed? That was my only concern of just searching by name. I can certainly go back and see if I missed anything when we figure out what's going on with pasting the syntax thing. I hope my terminology is being used correctly and isn't confusing you! :) These letters from CP seemed to go pretty well. I see above that I must have an extra line perhaps?

2019-03-12 13:57 UTC, jaredh159 commented
@maijapapaya if you end up working today some, slack me and let's do a quick screen share, I'd like to investigate this more so I can fix the problem.

2019-03-13 13:02 UTC, jaredh159 requested changes
Maija, 

You did super good work here, I only found a couple mistakes. I did leave a ton of comments though, and that's because reviewing this reminded me of two things I forgot to teach you about.  Really sorry about that, I feel bad causing you a bunch of extra work. If you have any questions or want to go over the concepts on skype, I'd be happy to.

2019-03-13 13:02 UTC, jaredh159 commented on life-and-letters/modernized/02-chapter-2.adoc
> +[.embedded-content-document.letter]
Maija, this work looks just about perfect. 😄 

Except... for something I totally forgot to tell you, sorry!

So, if a letter has a _heading directly above it_, then we put the heading **inside** the embedded document. So, in this case, it should be:

```ASCIIDOC
[.embedded-content-document.letter]
--

[.blurb]
=== Copy of a Letter to that truly great minister, my ancient friend, Abigail Watson of Ireland.

[.signed-section-context-open]
Dudley, 18th of Eleventh month, 1751.

etc...
```

The other really common type of a heading is our `[.letter-heading]` -- these should also go **inside** the embedded document, like this:

```ASCIIDOC
[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Neale to Sarah Grubb

The hand and judgments of the Lord are to be laid upon
every of his vessels and instruments in his house,
for their being fitted and formed according to the will and wisdom of Him,
being written in the aboundings of that love which
fills a heart that wishes you prosperity in every sense;
I am, your very affectionate friend,

[.signed-section-signature]
Samuel Neale.

--
```

So, unfortunately there are a bunch of these in this doc, I'll make a note on each one.  Again, sorry about forgetting to show you this!

So for this particular line, the letter open should be above the blurb-header above 👍

2019-03-13 13:02 UTC, jaredh159 commented on life-and-letters/modernized/02-chapter-2.adoc
> +[.embedded-content-document.epistle]
same here, move above `[.blurb]` heading

2019-03-13 13:02 UTC, jaredh159 commented on life-and-letters/modernized/03-chapter-3.adoc
> +[.embedded-content-document.letter]
same here, move above `[.blurb]` heading

2019-03-13 13:02 UTC, jaredh159 commented on life-and-letters/modernized/04-chapter-4.adoc
> +[.embedded-content-document.letter]
same here, move above `[.blurb]` heading

2019-03-13 13:02 UTC, jaredh159 commented on life-and-letters/modernized/06-chapter-6.adoc
> +[.embedded-content-document.letter]
same here, move above `[.blurb]` heading

2019-03-13 13:02 UTC, jaredh159 commented on life-and-letters/modernized/06-chapter-6.adoc
> +[.embedded-content-document.letter]
same here, move above `[.blurb]` heading

2019-03-13 13:02 UTC, jaredh159 commented on life-and-letters/modernized/07-chapter-7.adoc
> +[.embedded-content-document.epistle]
same here, move above `[.blurb]` heading

2019-03-13 13:02 UTC, jaredh159 commented on life-and-letters/modernized/08-chapter-8.adoc
> +[.embedded-content-document.letter]
whoops, it looks like this one got put in the wrong spot, it should be moved _above_ the `[.signed-section-context-open]` on line 681.

2019-03-13 13:02 UTC, jaredh159 commented on life-and-letters/modernized/08-chapter-8.adoc
> +[.embedded-content-document.letter]
same here, move above `[.blurb]` heading

2019-03-13 13:02 UTC, jaredh159 commented on life-and-letters/modernized/08-chapter-8.adoc
> +[.embedded-content-document.letter]
same here, move above `[.blurb]` heading

2019-03-13 13:02 UTC, jaredh159 commented on life-and-letters/modernized/08-chapter-8.adoc
> +[.embedded-content-document.letter]
Ok, so here's another thing I forgot to mention.  If you ever run across a case like this, where two letters are back to back, with an "asterism" (that means `* * *` in the books) or a "small-break"  _between_ them, then I want you to **remove the asterism**. That's because before we had invented the "embedded document" concept, two letters back to back would look weird and funny, so I put the asterism or break between the letters to break them up. But, now that we have the embedded content document wrappers, we don't need this, so these should be removed. So, can you remove the two lines that read:

```ASCIIDOC
[.asterism]
'''
```

2019-03-13 13:02 UTC, jaredh159 commented on life-and-letters/modernized/09-chapter-9.adoc
> +[.embedded-content-document.letter]
same here, move above `[.blurb]` heading

2019-03-13 13:02 UTC, jaredh159 commented on life-and-letters/modernized/09-chapter-9.adoc
> +[.embedded-content-document.letter]
there's an asterism above this one that should be nixed as well. ^

2019-03-13 13:02 UTC, jaredh159 commented on life-and-letters/modernized/09-chapter-9.adoc
> +[.embedded-content-document.letter]
same here, move above `[.blurb]` heading

AND, remove the asterism between :)

2019-03-13 13:02 UTC, jaredh159 commented on life-and-letters/original/02-chapter-2.adoc
> +[.embedded-content-document.letter]
same here, move above `[.blurb]` heading

2019-03-13 13:02 UTC, jaredh159 commented on life-and-letters/original/02-chapter-2.adoc
> +[.embedded-content-document.epistle]
same here, move above `[.blurb]` heading

2019-03-13 13:02 UTC, jaredh159 commented on life-and-letters/original/03-chapter-3.adoc
> +
hmmm... it looks like below this line we missed a letter (around lines 450-455 is near it's beginning)

2019-03-13 13:02 UTC, jaredh159 commented on life-and-letters/original/04-chapter-4.adoc
> +[.embedded-content-document.letter]
same here, move above `[.blurb]` heading

2019-03-13 13:02 UTC, jaredh159 commented on life-and-letters/original/06-chapter-6.adoc
> +[.embedded-content-document.letter]
same here, move above `[.blurb]` heading

2019-03-13 13:02 UTC, jaredh159 commented on life-and-letters/original/07-chapter-7.adoc
> +[.embedded-content-document.epistle]
same here, move above `[.blurb]` heading

2019-03-13 13:02 UTC, jaredh159 commented on life-and-letters/original/08-chapter-8.adoc
> +[.embedded-content-document.letter]
this one also (maybe it's the same one, just in the original?) got inserted to low, it should be above the context-open chunk above.

2019-03-13 13:02 UTC, jaredh159 commented on life-and-letters/original/08-chapter-8.adoc
> +[.embedded-content-document.letter]
this one also needs to go above the context-open.

2019-03-13 13:02 UTC, jaredh159 commented on life-and-letters/original/08-chapter-8.adoc
> +[.embedded-content-document.letter]
same here, move above `[.blurb]` heading

2019-03-13 13:02 UTC, jaredh159 commented on life-and-letters/original/08-chapter-8.adoc
> +[.embedded-content-document.letter]
kill the asterism above

2019-03-13 13:02 UTC, jaredh159 commented on life-and-letters/original/09-chapter-9.adoc
> +[.embedded-content-document.letter]
same here, move above `[.blurb]` heading

2019-03-13 13:02 UTC, jaredh159 commented on life-and-letters/original/09-chapter-9.adoc
> +[.embedded-content-document.letter]
nix asterism above ^

2019-03-13 13:02 UTC, jaredh159 commented on life-and-letters/original/09-chapter-9.adoc
> +[.embedded-content-document.letter]
same here, move above `[.blurb]` heading

AND, nix the asterism.

2019-03-13 16:36 UTC, maijapapaya commented on life-and-letters/original/03-chapter-3.adoc
> +
I might have already corrected this when I was going through the modernized...I made the corrections in the modernized and then immediately corrected them in the original too. I don't see a problem looking at it now, but let me know if I still missed it.

2019-03-15 14:11 UTC, jaredh159 approved these changes

2019-03-15 14:12 UTC, merged

2019-03-15 14:12 UTC, jaredh159 commented
Looks good Maija, merging. :)